Remove reference to setPreserveJsDocWhitespace
`options.setPreserveJsDocWhitespace` is deprecated and removed. As-is, when built with the head compiler, this code throws: `1) Error in custom provider, java.lang.NoSuchMethodError: com.google.javascript.jscomp.CompilerOptions.setPreserveJsDocWhitespace(Z)V`.

The new replacement option `setParseJsDocDocumentation` is called implicitly with the equivalent value in `setIdeMode`s implementation.